'use client';
import { useEffect, useState } from 'react';
import { useApp } from '@/contexts/AppContext';
import { useLibrary } from '@/contexts/LibraryContext';
import { fetchAnnouncements, saveAnnouncement, deleteAnnouncement, type Announcement, type NoticeDestination } from '@/lib/announcements';
const blank={title:'',excerpt:'',body:'',destination:'' as NoticeDestination|'',destination_id:''};
export function AdminAnnouncements(){
 const {showToast,showError,confirm}=useApp(),library=useLibrary();
 const [items,setItems]=useState<Announcement[]>([]),[loading,setLoading]=useState(true),[failed,setFailed]=useState(false),[version,setVersion]=useState(0),[busy,setBusy]=useState(false),[editing,setEditing]=useState<Announcement|null>(null),[form,setForm]=useState(blank);
 useEffect(()=>{let active=true;const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);Promise.resolve().then(()=>{if(active){setLoading(true);setFailed(false);}});fetchAnnouncements(true,controller.signal).then(data=>{if(active)setItems(data);}).catch(()=>{if(active)setFailed(true);}).finally(()=>{clearTimeout(timer);if(active)setLoading(false);});return()=>{active=false;controller.abort();clearTimeout(timer);};},[version]);
 const save=async(publish:boolean)=>{
  if(busy||!form.title.trim()||!form.body.trim())return;
  if((form.destination==='club'||form.destination==='article')&&!form.destination_id.trim()){showError(new Error('Informe o ID de destino'));return;}
  setBusy(true);
  try{await saveAnnouncement({title:form.title.trim(),excerpt:form.excerpt.trim(),body:form.body.trim(),destination:form.destination||null,destination_id:form.destination&&['club','article','jogos','tournaments','subscription'].includes(form.destination)?form.destination_id.trim()||null:null,published_at:publish?editing?.published_at??new Date().toISOString():null},editing?.id);setEditing(null);setForm(blank);setVersion(v=>v+1);library.refresh();showToast(publish?'Aviso publicado':'Rascunho salvo');}catch(e){showError(e);}finally{setBusy(false);}
 };
 return <section style={{padding:16,display:'grid',gap:16}}><h2 style={{margin:0}}>Avisos</h2><form onSubmit={e=>{e.preventDefault();void save(false);}} style={{display:'grid',gap:12}}>
 <label>Título<input className="input" required maxLength={160} value={form.title} onChange={e=>setForm(f=>({...f,title:e.target.value}))}/></label><label>Resumo<input className="input" maxLength={320} value={form.excerpt} onChange={e=>setForm(f=>({...f,excerpt:e.target.value}))}/></label><label>Aviso<textarea className="input" required maxLength={12000} rows={5} value={form.body} onChange={e=>setForm(f=>({...f,body:e.target.value}))}/></label>
 <label>Destino<select className="input" value={form.destination} onChange={e=>setForm(f=>({...f,destination:e.target.value as NoticeDestination|'',destination_id:''}))}><option value="">Sem botão</option>{Object.entries({jogos:'Jogos',tournaments:'Classificação',club:'Clube',article:'Notícia',subscription:'Inscrições',rules:'Regulamento',saved:'Salvos'}).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
 {form.destination&&['club','article','jogos','tournaments','subscription'].includes(form.destination)&&<label>ID de destino{['club','article'].includes(form.destination)?' (obrigatório)':' (opcional)'}<input className="input" value={form.destination_id} onChange={e=>setForm(f=>({...f,destination_id:e.target.value}))}/></label>}
 <div style={{display:'flex',flexWrap:'wrap',gap:8}}><button className="btn btn-tonal" disabled={busy} type="submit">Salvar rascunho</button><button className="btn btn-primary" disabled={busy||!form.title.trim()||!form.body.trim()} type="button" onClick={()=>void save(true)}>Publicar aviso</button>{editing&&<button className="btn btn-outlined" type="button" onClick={()=>{setEditing(null);setForm(blank);}}>Cancelar edição</button>}</div></form>
 {loading?<p role="status">Carregando avisos…</p>:failed?<button className="btn btn-tonal" onClick={()=>setVersion(v=>v+1)}>Tentar novamente</button>:!items.length?<p>Nenhum aviso criado.</p>:items.map(item=><div key={item.id} style={{padding:16,borderRadius:16,background:'var(--surface-c)',display:'flex',alignItems:'center',flexWrap:'wrap',gap:12}}><div style={{flex:1,minWidth:140}}><strong>{item.title}</strong><div style={{fontSize:12,color:'var(--on-surface-variant)'}}>{item.published_at?'Publicado':'Rascunho'}</div></div><button className="btn btn-tonal" type="button" onClick={()=>{setEditing(item);setForm({title:item.title,excerpt:item.excerpt,body:item.body,destination:item.destination??'',destination_id:item.destination_id??''});}}>Editar</button><button className="btn btn-outlined" type="button" disabled={busy} onClick={async()=>{if(!await confirm({title:'Excluir aviso?',confirmLabel:'Excluir',danger:true}))return;setBusy(true);try{await deleteAnnouncement(item.id);setVersion(v=>v+1);library.refresh();if(editing?.id===item.id){setEditing(null);setForm(blank);}}catch(e){showError(e);}finally{setBusy(false);}}}>Excluir</button></div>)}
 </section>;
}
